[project]
name = "图像分类项目"
task_type = "classification"
created_at = "2025-08-07T15:24:44.933065"
description = "猫狗分类项目"

[datasets]
available = []
current = ""

[models]
available = []
current = ""
pretrained = []

[training]
history = []

[training.parameters]
epochs = 100
batch_size = 16
learning_rate = 0.01
image_size = 640

[custom_fields]
