[project]
name = "test2"
task_type = "detection"
created_at = "2025-08-08T15:02:21.935855"
description = ""

[datasets]
available = []
current = ""
detailed = []

[models]
available = []
current = ""
pretrained = []

[training]
history = []

[training.parameters]
epochs = 100
batch_size = 16
learning_rate = 0.01
image_size = 640

[custom_fields]
