[project]
name = "YOLO目标检测项目"
task_type = "detection"
created_at = "2025-08-07T15:24:44.918963"
description = "用于车辆检测的YOLO项目"

[datasets]
available = []
current = ""

[models]
available = []
current = ""
pretrained = []

[training]
history = []

[training.parameters]
epochs = 100
batch_size = 16
learning_rate = 0.01
image_size = 640

[custom_fields]
